/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                   '#ebb2ff',
        'on-primary':                '#520071',
        'primary-container':         '#7b1fa2',
        'on-primary-container':      '#e8aaff',
        'primary-fixed':             '#f8d8ff',
        'primary-fixed-dim':         '#ebb2ff',
        'on-primary-fixed':          '#320047',
        'on-primary-fixed-variant':  '#721199',
        'inverse-primary':           '#8c33b3',

        'secondary':                 '#f8bd2a',
        'on-secondary':              '#402d00',
        'secondary-container':       '#d9a200',
        'on-secondary-container':    '#533c00',
        'secondary-fixed':           '#ffdfa0',
        'secondary-fixed-dim':       '#f8bd2a',
        'on-secondary-fixed':        '#261a00',
        'on-secondary-fixed-variant':'#5c4300',

        'tertiary':                  '#d7baff',
        'on-tertiary':               '#430585',
        'tertiary-container':        '#6334a5',
        'on-tertiary-container':     '#d2b3ff',
        'tertiary-fixed':            '#eddcff',
        'tertiary-fixed-dim':        '#d7baff',
        'on-tertiary-fixed':         '#280056',
        'on-tertiary-fixed-variant': '#5a2a9c',

        // Landing-specific warm gold tertiary (as in HTML original)
        'landing-tertiary':          '#e8c170',

        'error':                     '#ffb4ab',
        'on-error':                  '#690005',
        'error-container':           '#93000a',
        'on-error-container':        '#ffdad6',

        'background':                '#131313',
        'on-background':             '#e5e2e1',
        'surface':                   '#131313',
        'on-surface':                '#e5e2e1',
        'surface-dim':               '#131313',
        'surface-bright':            '#393939',
        'surface-variant':           '#353534',
        'on-surface-variant':        '#d2c1d3',
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1c1b1b',
        'surface-container':         '#201f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-tint':              '#ebb2ff',

        'outline':                   '#9b8c9c',
        'outline-variant':           '#4e4351',
        'inverse-surface':           '#e5e2e1',
        'inverse-on-surface':        '#313030',
      },
      fontFamily: {
        // Landing/auth/SWAR pages: Bodoni Moda for display & headlines
        'display-lg':  ['"Bodoni Moda"', 'serif'],
        'headline-xl': ['"Bodoni Moda"', 'serif'],
        'headline-md': ['"Bodoni Moda"', 'serif'],
        // App pages: Montserrat
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-lg':     ['Montserrat', 'sans-serif'],
        'body-md':     ['Montserrat', 'sans-serif'],
        'label-md':    ['Montserrat', 'sans-serif'],
        'label-sm':    ['Montserrat', 'sans-serif'],
        'label-caps':  ['Montserrat', 'sans-serif'],
        'bodoni':      ['"Bodoni Moda"', 'serif'],
      },
      fontSize: {
        'display-lg':  ['clamp(48px,6vw,72px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['48px', { lineHeight: '56px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg':     ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md':    ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '500' }],
        'label-caps':  ['12px', { lineHeight: '16px', letterSpacing: '0.1em',  fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
