# Generated by Django 6.0.5 on 2026-05-23 09:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('rating', models.CharField(choices=[('safe', 'Safe'), ('unsafe', 'Unsafe')], max_length=10)),
                ('comment', models.TextField(blank=True, default='')),
                ('time_of_day', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Suraksha Premium'), ('org', 'Organisation')], default='free', max_length=20)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('tokens_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('sos_contact_1', models.CharField(blank=True, default='', max_length=20)),
                ('sos_contact_2', models.CharField(blank=True, default='', max_length=20)),
                ('sos_contact_3', models.CharField(blank=True, default='', max_length=20)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
